apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: web
  annotations:
    github.com/project-slug: nelsonkopliku/web
    backstage.io/adr-location: adr
spec:
  type: other
  lifecycle: unknown
  owner: guests
